{
 "title": "Site Overview",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "RTU", "query": "select topic_name from topics" }
  ]
 },
 "panels": [
  {
   "title": "EL - Occupancy Status",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(ts, $__interval) AS time,\r\n  MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU01' THEN cast(value_string as float) END) AS RTU01,\r\n  MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU02' THEN cast(value_string as float) END) AS RTU02,\r\n  MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU03' THEN cast(value_string as float) END) AS RTU03,\r\n  MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU04' THEN cast(value_string as float) END) AS RTU04\r\nFROM data\r\nNATURAL JOIN topics\r\nWHERE topic_name LIKE 'PNNL/ROB/%/OccupancyCommand'\r\n  AND $__timeFilter(ts)\r\nGROUP BY 1\r\nORDER BY 1\r\n"
    }
   ]
  },
  {
   "title": "EL - Occupancy Setpoint Error",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "WITH zone_temps AS (\r\n  SELECT\r\n    $__timeGroup(ts, $__interval) AS time,\r\n    MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU01' THEN cast(value_string as float) END) AS RTU01_temp,\r\n    MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU02' THEN cast(value_string as float) END) AS RTU02_temp,\r\n    MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU03' THEN cast(value_string as float) END) AS RTU03_temp,\r\n    MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU04' THEN cast(value_string as float) END) AS RTU04_temp\r\n  FROM data\r\n  NATURAL JOIN topics\r\n  WHERE topic_name LIKE 'PNNL/ROB/%/ZoneTemperature'\r\n    AND $__timeFilter(ts)\r\n  GROUP BY 1\r\n),\r\nzone_setpoints AS (\r\n  SELECT\r\n    $__timeGroup(ts, $__interval) AS time,\r\n    MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU01' THEN cast(value_string as float) END) AS RTU01_sp,\r\n    MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU02' THEN cast(value_string as float) END) AS RTU02_sp,\r\n    MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU03' THEN cast(value_string as float) END) AS RTU03_sp,\r\n    MAX(CASE WHEN upper(split_part(topic_name, '/', 3)) = 'RTU04' THEN cast(value_string as float) END) AS RTU04_sp\r\n  FROM data\r\n  NATURAL JOIN topics\r\n  WHERE topic_name LIKE 'PNNL/ROB/%/EffectiveZoneTemperatureSetPoint'\r\n    AND $__timeFilter(ts)\r\n  GROUP BY 1\r\n)\r\nSELECT\r\n  t.time,\r\n  t.RTU01_temp - s.RTU01_sp AS RTU01,\r\n  t.RTU02_temp - s.RTU02_sp AS RTU02,\r\n  t.RTU03_temp - s.RTU03_sp AS RTU03,\r\n  t.RTU04_temp - s.RTU04_sp AS RTU04\r\nFROM zone_temps t\r\nJOIN zone_setpoints s ON t.time = s.time\r\nORDER BY t.time\r\n"
    }
   ]
  },
  {
   "title": "EL - $RTU Status",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"EffectiveZoneTemperatureSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU/EffectiveZoneTemperatureSetPoint' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"ZoneHumidity\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU/ZoneHumidity' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"OccupiedCoolingSetPoint\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU/OccupiedCoolingSetPoint' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"SupplyFanStatus\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU/SupplyFanStatus' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"ZoneTemperature\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU/ZoneTemperature' AND $__timeFilter(ts) ORDER BY 1;\r\n"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"OutdoorAirTemperature\" from data natural join topics where topic_name like 'PNNL/ROB/%/OutdoorAirTemperature' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"CoolingStage\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU/%StageCooling' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"HeatingStage\" from data natural join topics where topic_name like 'PNNL/ROB/$RTU/%StageHeating' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "EL - Weather",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"Outdoor Air Temperature\" from data natural join topics where topic_name like 'PNNL/ROB/%/OutdoorAirTemperature' AND $__timeFilter(ts) ORDER BY 1;"
    },
    {
     "rawSql": "SELECT ts as \"time\", cast(value_string as float) as \"Air temperature\" from data natural join topics where topic_name like '%/%/air_temperature' AND $__timeFilter(ts) ORDER BY 1;"
    }
   ]
  },
  {
   "title": "EL - Building Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "\r\nSELECT\r\n  ts as \"time\",\r\n  cast(value_string as float)/1000 as \"Instantaneous Power\",\r\n  AVG(cast(value_string as float)/1000) OVER (\r\n    ORDER BY ts\r\n    RANGE BETWEEN INTERVAL '30 minutes' PRECEDING AND '0 minutes' FOLLOWING\r\n  ) AS \"30 Min. Avg. Power\",\r\n  AVG(cast(value_string as float)/1000) OVER (\r\n    ORDER BY ts\r\n    RANGE BETWEEN INTERVAL '15 minutes' PRECEDING AND '15 minutes' FOLLOWING\r\n  ) AS \"15 Min. Avg. Power\"\r\nFROM\r\n  data\r\nnatural join topics where\r\n  topic_name = 'PNNL/ROB/meter/Watts'\r\n  AND $__timeFilter(ts)\r\nORDER BY\r\n  ts;"
    }
   ]
  }
 ]
}